version: 2.1

orbs:
  docker: circleci/docker@2.8.2

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:

  release_image:
    docker:
      - image: harbor.k8s.libraries.psu.edu/library/ci-utils:$CI_UTILS_IMG_TAG
    environment:
      REGISTRY_HOST: harbor.k8s.libraries.psu.edu
      GITHUB_USER: 'psu-stewardship-bot'
      CONFIG_REPO: git@github.com:psu-libraries/drupal-site-config.git
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: "Release"
          command: |
            export REGISTRY_REPO="library/$CIRCLE_PROJECT_REPONAME"
            /usr/local/bin/tag-image
            ssh-keyscan github.com > ~/.ssh/known_hosts
            git clone $CONFIG_REPO
            cd drupal-site-config
            /usr/local/bin/pr-release clusters/prod/manifests/$CIRCLE_PROJECT_REPONAME/prod.yaml

  build-and-push:
    parameters:
      version:
        type: string
    executor:
      name: docker/docker
      tag: "3.8"
    environment:
      REGISTRY_HOST: harbor.k8s.libraries.psu.edu
    steps:
    - setup_remote_docker
    - checkout
    - docker/check:
        registry: $REGISTRY_HOST
    - docker/build:
        extra_build_args: "--secret id=COMPOSER_AUTH,env=COMPOSER_AUTH"
        image: "library/$CIRCLE_PROJECT_REPONAME"
        registry: $REGISTRY_HOST
        use-buildkit: true
        tag: << parameters.version >>
    - docker/push:
        registry: $REGISTRY_HOST
        image: "library/$CIRCLE_PROJECT_REPONAME"
        tag: << parameters.version >>

  deploy:
    docker:
      - image: harbor.k8s.libraries.psu.edu/library/ci-utils:$CI_UTILS_IMG_TAG
    environment:
      CONFIG_REPO: git@github.com:psu-libraries/drupal-site-config.git
    parameters:
      config_env:
        type: string
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: "Updating Config Repo"
          command: |
            export CONFIG_ENV=<< parameters.config_env >>
            ssh-keyscan github.com > ~/.ssh/known_hosts
            git clone $CONFIG_REPO
            cd drupal-site-config
            ./bin/generate_app

  delete-deployment:
    docker:
      - image: harbor.k8s.libraries.psu.edu/library/ci-utils:$CI_UTILS_IMG_TAG
    environment:
      CONFIG_REPO: git@github.com:psu-libraries/drupal-site-config.git
    parameters:
      config_env:
        type: string
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: "Updating Config Repo"
          command: |
            export CONFIG_ENV=<< parameters.config_env >>
            ssh-keyscan github.com > ~/.ssh/known_hosts
            git clone $CONFIG_REPO
            cd drupal-site-config
            ./bin/delete-deployment

  drupal-updater:
    docker:
      - image: harbor.k8s.libraries.psu.edu/library/ci-utils:v4.1.0
    environment:
      CONFIG_REPO: git@github.com:psu-libraries/drupal-site-config.git
    parameters:
      config_env:
        type: string
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: "Deploy Drupal Updater"
          command: |
            export CONFIG_ENV=<< parameters.config_env >>
            ssh-keyscan github.com > ~/.ssh/known_hosts
            git clone $CONFIG_REPO
            cd drupal-site-config
            ./bin/generate_app_update

workflows:
  delete-deployment:
    when:
      equal: [ "delete", << pipeline.parameters.GHA_Event >> ]
      
    jobs:
      - delete-deployment:
          context:
            - org-global
          config_env: dev
          filters:
            branches:
              only:
                - /update\/.*/
  docker_push:
    jobs:
      - release_image:
          context:
            - org-global
          name: "release image"
          filters:
            tags:
              only:
                - /^v\d+.\d+.\d+.*/
            branches:
              ignore:
                  - /.*/
      - build-and-push:
          context:
            - org-global
          version: "$CIRCLE_SHA1"
          filters:
            branches:
              only:
                - main
                - /preview\/.*/
                - /updater\/.*/
      - deploy:
          context:
            - org-global
          config_env: qa
          requires:
            - build-and-push
          filters:
            branches:
              only:
                - main
      - deploy:
          context:
            - org-global
          config_env: dev
          requires:
            - build-and-push
          filters:
            branches:
              only:
                - /preview\/.*/
      - drupal-updater:
          context:
            - org-global
          config_env: dev
          requires:
            - build-and-push
          filters:
            branches:
              only:
                - /updater\/.*/
