#!/bin/sh

# ====================================
#  clean database
# ====================================

drush site:install --existing-config -y



# ====================================
#  configure ssh
# ====================================

mkdir /home/drupal/.ssh
echo  "$CIRCLE_SSH_KEY" > /home/drupal/.ssh/id_rsa_circle
chmod 600 /home/drupal/.ssh/id_rsa_circle
ssh-keyscan github.com >> ~/.ssh/known_hosts



# ====================================
#  configure git
# ====================================

git config --global --add safe.directory /var/www/html

git config --global user.email "lst-apps-integration@PennStateOffice365.onmicrosoft.com"
git config --global user.name "Drupal Magic Script"

git config --local core.sshCommand "/usr/bin/ssh -i /home/drupal/.ssh/id_rsa_circle"


# ====================================
#  checkout branch with unique name
# ====================================

uid=$(cat /proc/sys/kernel/random/uuid)

git checkout -b drupal-updater-$uid



# ====================================
#  install and run drupal-updater
# ====================================

composer config --global github-oauth.github.com $GITHUB_TOKEN

composer require metadrop/drupal-updater

drupal-updater update --config /usr/local/etc/drupal-updater-config.yml

composer remove metadrop/drupal-updater



# ====================================
#  create pull request
# ====================================

git add -A
git commit --no-verify -a -m "drupal-updater: $uid"
git push -u origin drupal-updater-$uid

gh pr create \
    --title "release drupal-updater-$uid" \
    --body "release drupal-updater-$uid" \
    --base main
