
name: delete-deployment
on: 
  delete
jobs:
  delete-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: delete-deployment
        id: delete-deployment
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        with:
          target_slug: "github/psu-libraries/jimtest"
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
        continue-on-error: true
      - name: Print CircleCI Response
        run: echo '${{ steps.delete-deployment.outputs.circleci_response }}'
