name: renovate
run-name: jimtest-renovate
on: [push]
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.2
        with:
          configurationFile: renovate.json
          renovate-version: 39.8.0
          token: ${{ secrets.RENOVATE_TOKEN }}
    env:
      LOG_LEVEL: DEBUG
